name: dart_repl
description: A Dart REPL proof of concept inspired by Python's interactive mode.
version: 0.11.1
author: Andreas 'blackhc' Kirsch <blackhc@gmail.com>
homepage: https://blog.blackhc.net

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  args: ">=0.13.7 <0.14.0"
  vm_service_client:
    git:
      url: git://github.com/BlackHC/vm_service_client.git
      ref: reload_sources_poc
  analyzer: ">=0.29.2 <0.30.0"
  package_resolver: ">=1.0.2 <2.0.0"
  meta: ">=1.0.4 <2.0.0"
  pub_cache: ">=0.1.0 <0.2.0"
  dart_repl_sandbox: ">=0.11.1 <0.12.0"

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
